name: Deploy Twilio Functions

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{github.ref_name}}

    steps:
      - name: Use Qoomon Context
        id: qoomon-context
        uses: qoomon/actions--context@v4
        run: |
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "GITHUB_REF=${GITHUB_EVIRONMENT}}"
        

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Twilio CLI and plugins
        run: |
          npm install -g twilio-cli
          twilio plugins:install @twilio-labs/plugin-serverless

      - name: Deploy Twilio Functions to environment ${{github.ref_name}}
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        run: |
          twilio serverless:deploy --username $TWILIO_ACCOUNT_SID --password $TWILIO_AUTH_TOKEN --environment=dev --force